CREATE TABLE [dbo].[Customers](	  [CustomerID] NCHAR(5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	, [CompanyName] NVARCHAR(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	, [ContactName] NVARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [ContactTitle] NVARCHAR(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [Address] NVARCHAR(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [City] NVARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [Region] NVARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [PostalCode] NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [Country] NVARCHAR(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [Phone] NVARCHAR(24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, [Fax] NVARCHAR(24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	, CONSTRAINT [PK_Customers] PRIMARY KEY ([CustomerID] ASC))CREATE CLUSTERED COLUMNSTORE INDEX IX_Customers_History	ON dbo.CustomersSELECT *FROM dbo.CustomersALTER TABLE dbo.Customers
  ADD
        SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
            CONSTRAINT DF_SysStart DEFAULT SYSUTCDATETIME()
      , SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
            CONSTRAINT DF_SysEnd DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59'),
        PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);ALTER TABLE dbo.Customers
  ADD SysStartTime datetime2 GENERATED ALWAYS AS ROW START  DEFAULT(SYSUTCDATETIME()) NOT NULL 
  ,SysEndTime datetime2 GENERATED ALWAYS AS ROW END  DEFAULT(SYSUTCDATETIME()) NOT NULL 
	,PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime)


ALTER TABLE dbo.Customers
	A

ALTER TABLE dbo.Customers
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Customers_History))